<?php

if(!$block->checkIsLoomisShipment()) {
    return ;
}

?>
<br>

<section class="admin__page-section" style="max-width: 500px;">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Loomis Shipment Options') ?></span>
    </div>
    <div class="admin__page-section-item">
      <table width="100%">
        <tr>
          <td>Shipment Cost centre</td>
          <td class="admin__field-option"><input type="text" name="reference_loomis_1" /></td>
        </tr>
        <tr>
          <td>Shipment Reference</td>
          <td class="admin__field-option"><input type="text" name="reference_loomis_2" /></td>
        </tr>
      </table>
    </div>
</section>
